version: '3'

services:
  pal-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USERNAME: 'user'
    ports:
      - '3306:3306'
  pal-db-test:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USERNAME: 'user'
    ports:
      - '3307:3306'