spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    clean-on-validation-error: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"